# Generated by Django 6.0 on 2026-02-06 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='شعار الشركة')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='صورة الملف الشخصي')),
                ('full_name', models.CharField(blank=True, max_length=100, verbose_name='الاسم الكامل')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('gender', models.CharField(blank=True, choices=[('M', 'ذكر'), ('F', 'أنثى'), ('O', 'آخر')], max_length=1, verbose_name='الجنس')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='المدينة')),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='البلد')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='الرمز البريدي')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='نبذة شخصية')),
                ('website', models.URLField(blank=True, verbose_name='الموقع الإلكتروني')),
                ('facebook', models.URLField(blank=True, verbose_name='فيسبوك')),
                ('twitter', models.URLField(blank=True, verbose_name='تويتر')),
                ('instagram', models.URLField(blank=True, verbose_name='انستغرام')),
                ('linkedin', models.URLField(blank=True, verbose_name='لينكدإن')),
                ('skills', models.CharField(blank=True, max_length=200, verbose_name='المهارات')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='الوظيفة')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='الشركة')),
                ('experience_years', models.PositiveIntegerField(blank=True, null=True, verbose_name='سنوات الخبرة')),
                ('education_level', models.CharField(blank=True, choices=[('HS', 'ثانوي'), ('DIP', 'دبلوم'), ('BAC', 'بكالوريوس'), ('MAS', 'ماجستير'), ('PHD', 'دكتوراه'), ('OTH', 'أخرى')], max_length=3, verbose_name='مستوى التعليم')),
                ('university_major', models.CharField(blank=True, max_length=100, verbose_name='التخصص الجامعي')),
                ('languages', models.CharField(blank=True, max_length=200, verbose_name='اللغات')),
                ('is_public', models.BooleanField(default=True, verbose_name='هل الملف الشخصي عام؟')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='تلقي إشعارات البريد الإلكتروني')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'الملف الشخصي',
                'verbose_name_plural': 'الملفات الشخصية',
            },
        ),
    ]
