# Generated by Django 6.0 on 2026-04-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='نظام الأزوردي', max_length=255, verbose_name='اسم الشركة')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='شعار الشركة')),
                ('contact_email', models.EmailField(default='info@example.com', max_length=254, verbose_name='البريد الإلكتروني')),
                ('contact_phone', models.CharField(default='+966 12 345 6789', max_length=20, verbose_name='رقم الهاتف')),
                ('contact_address', models.CharField(default='المملكة العربية السعودية', max_length=255, verbose_name='العنوان')),
                ('social_facebook', models.URLField(blank=True, null=True, verbose_name='فيسبوك')),
                ('social_twitter', models.URLField(blank=True, null=True, verbose_name='تويتر')),
                ('social_instagram', models.URLField(blank=True, null=True, verbose_name='انستغرام')),
                ('social_linkedin', models.URLField(blank=True, null=True, verbose_name='لينكد إن')),
            ],
            options={
                'verbose_name': 'إعدادات الشركة',
                'verbose_name_plural': 'إعدادات الشركة',
            },
        ),
    ]
