# Generated by Django 6.0 on 2026-04-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_companysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='footer_contact_title',
            field=models.CharField(default='تواصل معنا', max_length=100, verbose_name='عنوان التواصل'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='footer_copyright_text',
            field=models.CharField(default='جميع الحقوق محفوظة', max_length=255, verbose_name='نص حقوق النشر'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='footer_features_title',
            field=models.CharField(default='المميزات', max_length=100, verbose_name='عنوان المميزات'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='footer_quick_links_title',
            field=models.CharField(default='روابط سريعة', max_length=100, verbose_name='عنوان روابط سريعة'),
        ),
    ]
