# Generated by Django 6.0 on 2026-04-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_companysettings_footer_contact_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
    ]
