# Generated by Django 6.0 on 2026-04-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_companysettings_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='feature_inventory',
            field=models.URLField(blank=True, null=True, verbose_name='رابط إدارة المخزون'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='feature_invoices',
            field=models.URLField(blank=True, null=True, verbose_name='رابط إدارة الفواتير'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='feature_reports',
            field=models.URLField(blank=True, null=True, verbose_name='رابط التقارير الذكية'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='quick_link_faq',
            field=models.URLField(blank=True, null=True, verbose_name='رابط الأسئلة الشائعة'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='quick_link_guide',
            field=models.URLField(blank=True, null=True, verbose_name='رابط دليل الاستخدام'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='quick_link_support',
            field=models.URLField(blank=True, null=True, verbose_name='رابط الدعم الفني'),
        ),
    ]
