# Generated by Django 6.0 on 2026-04-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_companysettings_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='company_name',
            field=models.CharField(default='أدخل أسم شركتك  ', max_length=255, verbose_name='اسم الشركة'),
        ),
    ]
