# Generated by Django 6.0 on 2026-04-13 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_companysettings_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='whatsapp_message',
            field=models.CharField(blank=True, default='مرحباً، أتواصل معكم من المتجر، كيف يمكنكم مساعدتي؟', max_length=255, null=True, verbose_name='رسالة واتساب التلقائية'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الواتساب (مع رمز الدولة، مثال: 966501234567)'),
        ),
    ]
