# Generated by Django 6.0 on 2026-04-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_companysettings_whatsapp_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='fb_access_token',
            field=models.CharField(blank=True, help_text='أدخل الرمز الذي تحصل عليه من موقع مطوري فيسبوك (Developers Facebook). تنبيه: هذا الرمز سري، لا تشاركه مع أحد.', max_length=500, null=True, verbose_name='رمز الوصول الدائم (Access Token)'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='fb_page_id',
            field=models.CharField(blank=True, help_text='أدخل رقم المعرف الخاص بصفحتك على فيسبوك فقط.', max_length=100, null=True, verbose_name='معرف صفحة الفيسبوك (Page ID)'),
        ),
    ]
