# Generated by Django 6.0 on 2026-04-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_companysettings_fb_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('customer', 'زبون'), ('supplier', 'مورد')], default='customer', max_length=10, verbose_name='نوع المستخدم'),
        ),
    ]
