# Generated by Django 6.0 on 2026-03-12 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstoresetting',
            name='store_section',
            field=models.CharField(choices=[('none', 'بدون قسم (لا يظهر تلقائياً)'), ('offers', 'أحدث العروض'), ('new', 'منتجات جديدة'), ('products', 'منتجاتنا')], default='products', max_length=20, verbose_name='القسم في المتجر'),
        ),
        migrations.AlterField(
            model_name='productstoresetting',
            name='badge_image',
            field=models.ImageField(blank=True, null=True, upload_to='store_badges/', verbose_name='صورة الشعار'),
        ),
    ]
