# Generated by Django 6.0 on 2026-03-24 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_cart_websiteorder_websiteorderitem_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransaction',
            name='purchase_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions', to='invoice.purchasereturn', verbose_name='مرتجع المشتريات المرتبط'),
        ),
    ]
