# Generated by Django 6.0 on 2026-03-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_cashtransaction_purchase_return'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='مثال: خصم 50%', max_length=100, verbose_name='العنوان الترويجي')),
                ('image', models.ImageField(upload_to='store_banners/', verbose_name='صورة البنر')),
                ('link_url', models.URLField(blank=True, null=True, verbose_name='رابط عند الضغط')),
                ('position', models.CharField(choices=[('top', 'بنر علوي (عرض كامل)'), ('side', 'بنر جانبي')], default='top', max_length=10, verbose_name='موضع العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, help_text='الأقل يظهر أولاً', verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'بنر إعلاني',
                'verbose_name_plural': 'البنرات الإعلانية',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='productstoresetting',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتيب الظهور'),
        ),
        migrations.AddField(
            model_name='productstoresetting',
            name='show_old_price',
            field=models.BooleanField(default=True, verbose_name='إظهار السعر القديم'),
        ),
    ]
