# Generated by Django 6.0 on 2026-03-30 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_storebanner_productstoresetting_display_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productstoresetting',
            name='store_section',
        ),
        migrations.AddField(
            model_name='productstoresetting',
            name='store_sections',
            field=models.JSONField(blank=True, default=list, help_text="قائمة بأكواد الأقسام، مثال: ['offers', 'new']", verbose_name='أقسام المتجر'),
        ),
    ]
