# Generated by Django 6.0 on 2026-03-30 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_remove_productstoresetting_store_sections_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productstoresetting',
            name='store_section',
        ),
        migrations.AddField(
            model_name='productstoresetting',
            name='store_sections',
            field=models.JSONField(blank=True, default=list, verbose_name='أقسام المتجر'),
        ),
    ]
