# Generated by Django 6.0 on 2026-03-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_remove_productstoresetting_store_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productstoresetting',
            name='store_sections',
        ),
        migrations.AddField(
            model_name='productstoresetting',
            name='store_section',
            field=models.CharField(choices=[('none', 'بدون قسم (لا يظهر تلقائياً)'), ('offers', 'أحدث العروض'), ('new', 'منتجات جديدة'), ('products', 'منتجاتنا')], default='products', max_length=20, verbose_name='القسم في المتجر'),
        ),
    ]
