# Generated by Django 6.0 on 2026-03-30 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_remove_productstoresetting_store_sections_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثال: الأكثر مبيعاً', max_length=100, verbose_name='اسم القسم')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='الرابط النصي')),
                ('style_type', models.CharField(choices=[('grid', 'بطاقات شبكية (Grid)'), ('list', 'قائمة أفقية (List)'), ('offers', 'أسلوب العروض (Offers)')], default='grid', max_length=20, verbose_name='شكل العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال (يظهر في المتجر)')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='القسم ذو الرقم الأقل يظهر أولاً', verbose_name='ترتيب القسم')),
            ],
            options={
                'verbose_name': 'قسم متجر',
                'verbose_name_plural': 'أقسام المتجر',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductSectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب المنتج داخل القسم')),
                ('show_old_price', models.BooleanField(default=False, verbose_name='إظهار السعر القديم كعرض')),
                ('custom_badge', models.ImageField(blank=True, help_text='يظهر فوق صورة المنتج في هذا القسم فقط', null=True, upload_to='store_section_badges/', verbose_name='شعار خاص (اختياري)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.product', verbose_name='المنتج')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoice.storesection', verbose_name='القسم')),
            ],
            options={
                'verbose_name': 'منتج داخل القسم',
                'verbose_name_plural': 'منتجات الأقسام',
                'ordering': ['display_order'],
                'unique_together': {('section', 'product')},
            },
        ),
    ]
