# Generated by Django 6.0 on 2026-04-05 03:11

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_storesection_productsectionitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المستوى (مثال: أحدث العروض)')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='نسبة الخصم (%)')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'مستوى تسعير',
                'verbose_name_plural': 'مستويات التسعير',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductPriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='السعر المحسوب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_prices', to='invoice.product', verbose_name='المنتج')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='invoice.pricingtier', verbose_name='مستوى التسعير')),
            ],
            options={
                'verbose_name': 'سعر المنتج في مستوى',
                'verbose_name_plural': 'أسعار المستويات',
                'unique_together': {('product', 'tier')},
            },
        ),
    ]
