# Generated by Django 6.0 on 2026-04-05 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_pricingtier_productpricetier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم التصنيف')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='الرابط النصي')),
                ('is_active', models.BooleanField(default=True, verbose_name='ظاهر في المتجر')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب الظهور')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='categories_icons/', verbose_name='أيقونة التصنيف')),
                ('pricing_tier', models.ForeignKey(blank=True, help_text='إذا تم اختياره، سيتم استخدام سعر هذا المستوى للمنتجات التابعة لهذا التصنيف في المتجر', null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.pricingtier', verbose_name='مستوى التسعير الافتراضي')),
            ],
            options={
                'verbose_name': 'تصنيف',
                'verbose_name_plural': 'تصنيفات المتجر',
                'ordering': ['display_order'],
            },
        ),
    ]
