# Generated by Django 6.0 on 2026-04-05 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0012_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, help_text='اختر التصنيف الذي يتبع له هذا المنتج (اختياري)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='invoice.category', verbose_name='التصنيف'),
        ),
    ]
