# Generated by Django 6.0 on 2026-04-07 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0014_stocknotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocknotification',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='تم الإرسال'),
        ),
        migrations.AddField(
            model_name='stocknotification',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإرسال'),
        ),
    ]
