# Generated by Django 6.0 on 2026-04-09 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0015_stocknotification_is_sent_stocknotification_sent_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='سعر العرض')),
                ('max_quantity', models.PositiveIntegerField(default=1, help_text='عدد الوحدات المتاحة بهذا السعر. عندما تنتهي يختفي العرض.', verbose_name='الكمية المخصصة للعرض')),
                ('ends_at', models.DateTimeField(help_text='الوقت الذي يختفي فيه العرض تلقائياً', verbose_name='ينتهي في')),
                ('is_active', models.BooleanField(default=False, help_text='يعرض العرض في الصفحة الرئيسية فقط إذا كان مفعّلاً ولم ينتهِ وقته', verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'عرض فلاش',
                'verbose_name_plural': 'عروض الفلاش',
                'ordering': ['-created_at'],
            },
        ),
    ]
