# Generated by Django 6.0 on 2026-04-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0016_flashdeal'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreGlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcements', models.TextField(default='شحن مجاني للطلبات فوق 200 ر.س\nاستخدم كود خصم SAVE10 للحصول على خصم 10%\nضمان جودة على جميع المنتجات', help_text="اكتب كل إعلان في سطر جديد. يمكنك استخدام كود HTML للأيقونات مثل <i class='fas fa-truck'></i>.", verbose_name='شريط الإعلانات المتحرك')),
                ('features', models.TextField(default='شحن مجاني|fas fa-truck|fi-1\nضمان سنة|fas fa-shield-alt|fi-2\nاسترجاع 14 يوم|fas fa-undo|fi-3\nدفع آمن|fas fa-lock|fi-4', help_text='التنسيق: اسم الميزة | كود الأيقونة (مثال: fas fa-truck) | كود اللون (مثال: fi-1). كل ميزة في سطر جديد.', verbose_name='ميزات المتجر')),
            ],
            options={
                'verbose_name': 'إعدادات المتجر',
                'verbose_name_plural': 'إعدادات المتجر',
            },
        ),
    ]
