# Generated by Django 6.0 on 2026-04-10 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0017_storeglobalsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoreGlobalSettings',
        ),
    ]
