# Generated by Django 6.0 on 2026-04-10 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0018_delete_storeglobalsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='نص الإعلان')),
                ('icon_class', models.CharField(default='fa-bullhorn', help_text='مثال: fa-truck, fa-percent', max_length=50, verbose_name='كود الأيقونة (FontAwesome)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'إعلان شريط علوي',
                'verbose_name_plural': 'إعلانات الشريط العلوي',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StoreFeatureIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='العنوان')),
                ('icon_class', models.CharField(max_length=50, verbose_name='كود الأيقونة')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'أيقونة مميزة',
                'verbose_name_plural': 'الأيقونات المميزة',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeFlashSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='تفعيل العرض المزدوج في الرئيسية')),
                ('left_flash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_left', to='invoice.flashdeal', verbose_name='العرض الأيسر')),
                ('right_flash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_right', to='invoice.flashdeal', verbose_name='العرض الأيمن')),
            ],
            options={
                'verbose_name': 'إعداد فلاش الصفحة الرئيسية',
                'verbose_name_plural': 'إعدادات فلاش الرئيسية',
            },
        ),
    ]
