# Generated by Django 6.0 on 2026-04-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0019_storeannouncement_storefeatureicon_homeflashsplit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeannouncement',
            name='icon_class',
            field=models.CharField(default='fa-bullhorn', max_length=50, verbose_name='رمز الأيقونة (FontAwesome)'),
        ),
        migrations.AlterField(
            model_name='storefeatureicon',
            name='icon_class',
            field=models.CharField(max_length=50, verbose_name='رمز الأيقونة'),
        ),
        migrations.DeleteModel(
            name='HomeFlashSplit',
        ),
    ]
