# Generated by Django 6.0 on 2026-04-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0020_alter_storeannouncement_icon_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_barcode',
            field=models.CharField(blank=True, help_text='ادخل الرمز الشريطي الرئيسي للمنتج', max_length=100, null=True, unique=True, verbose_name='الباركود الأساسي'),
        ),
    ]
