# Generated by Django 6.0 on 2026-04-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0021_product_main_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_barcode',
            field=models.CharField(blank=True, help_text='ادخل الرمز الشريطي الرئيسي للمنتج', max_length=100, null=True, unique=True, verbose_name='الباركودالأساسي'),
        ),
    ]
